name: Delete Resource Group
on:
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for running the workflow
        required: false
        default: Manual run
      environment:
        description: "Select the Azure environment"
        required: true
        type: choice
        default: "development"
        options:
          - development
          - staging
          - production
# on:
#   push:
#     branches:
#       - main

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  infra-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Check if Resource Group Exists
        id: check_rsg
        uses: azure/cli@v2
        with:
          azcliversion: 2.64.0
          inlineScript: |
            az group show --name "${{ env.AZURE_RESOURCE_GROUP }}" >/dev/null 2>&1 || echo "not found"

      - name: Create Resource Group (if not exists)
        if: steps.check_rsg.outputs.exit_code == 'success'
        uses: azure/cli@v2
        with:
          azcliversion: 2.64.0
          inlineScript: |
            az group delete --name ${{ env.AZURE_RESOURCE_GROUP }} --yes
